// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmdhghabgaigqrbkinqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtZGhnaGFiZ2FpZ3FyYmtpbnFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzAxOTYsImV4cCI6MjA2NTkwNjE5Nn0.ChAuvojrH9tpCFWhWO893KPtizRbLzEOfmcAMsKxelE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);